CREATE TABLE Clients
(
	Id INT IDENTITY PRIMARY KEY, 
	FirstName NVARCHAR(30) NOT NULL, 
	LastName NVARCHAR(30) NOT NULL,
	Gender CHAR(1) CHECK(Gender = 'M' OR Gender = 'F'),
	BirthDate DATE,
	CreditCard NVARCHAR(30) NOT NULL, 
	CardValidity DATE, 
	Email NVARCHAR(50) NOT NULL
)

CREATE TABLE Towns
(
	Id INT IDENTITY PRIMARY KEY,
	Name NVARCHAR(50) NOT NULL
)

CREATE TABLE Offices
(
	Id INT IDENTITY PRIMARY KEY,
	[Name] NVARCHAR(40), 
	ParkingPlaces INT, 
	TownId INT FOREIGN KEY REFERENCES Towns(Id) NOT NULL
)

CREATE TABLE Models
(
	Id INT IDENTITY PRIMARY KEY,
	Manufacturer NVARCHAR(50) NOT NULL, 
	Model NVARCHAR(50) NOT NULL, 
	ProductionYear DATE, 
	Seats INT, 
	Class NVARCHAR(10), 
	Consumption DECIMAL(14,2)
)

CREATE TABLE Vehicles
(
	Id INT IDENTITY PRIMARY KEY, 
	ModelId INT NOT NULL FOREIGN KEY REFERENCES Models(Id),
	OfficeId INT NOT NULL FOREIGN KEY REFERENCES Offices(Id),
	Mileage INT
)

CREATE TABLE Orders
(
	Id INT IDENTITY PRIMARY KEY, 
	ClientId INT FOREIGN KEY REFERENCES Clients(Id) NOT NULL, 
	TownId INT FOREIGN KEY REFERENCES Towns(Id) NOT NULL,
	VehicleId INT FOREIGN KEY REFERENCES Vehicles(Id) NOT NULL,
	CollectionDate DATETIME NOT NULL, 
	CollectionOfficeId INT FOREIGN KEY REFERENCES Offices(Id) NOT NULL, 
	ReturnDate DATETIME, 
	ReturnOfficeId INT FOREIGN KEY REFERENCES Offices(Id),
	Bill DECIMAL(14,2), 
	TotalMileage INT
)

