CREATE TABLE Categories
(
	Id INT IDENTITY PRIMARY KEY, 
	[Name] NVARCHAR(30) NOT NULL
)

CREATE TABLE Items
(
	Id INT IDENTITY PRIMARY KEY, 
	[Name] NVARCHAR(30) NOT NULL,
	Price DECIMAL(15,2) NOT NULL, 
	CategoryId INT NOT NULL FOREIGN KEY REFERENCES Categories(Id)
)

CREATE TABLE Employees
(
	Id INT IDENTITY PRIMARY KEY, 
	FirstName NVARCHAR(50) NOT NULL,
	LastName NVARCHAR(50) NOT NULL,
	Phone CHAR(12) NOT NULL, 
	Salary DECIMAL(15,2) NOT NULL
)

CREATE TABLE Orders
(
	Id INT IDENTITY PRIMARY KEY, 
	[DateTime] DATETIME NOT NULL, 
	EmployeeId INT NOT NULL FOREIGN KEY REFERENCES Employees(Id)
)

CREATE TABLE OrderItems
(
	OrderId INT NOT NULL FOREIGN KEY REFERENCES Orders(Id), 
	ItemId INT NOT NULL FOREIGN KEY REFERENCES Items(Id), 
	Quantity INT NOT NULL CHECK(Quantity >= 1), 

	CONSTRAINT PK_Order_Item
	PRIMARY KEY (OrderId, ItemId)
)

CREATE TABLE Shifts
(
	Id INT IDENTITY NOT NULL, 
	EmployeeId INT NOT NULL FOREIGN KEY REFERENCES Employees(Id), 
	CheckIn DATETIME NOT NULL, 
	CheckOut DATETIME NOT NULL, 

	CONSTRAINT CHK_DATETIME
	CHECK (CheckOut > CheckIn), 

	CONSTRAINT PK_ID_EmployeeID
	PRIMARY KEY (Id, EmployeeId)
)